name: forest_tagger
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  firebase_core : ^0.5.0
  cupertino_icons: ^1.0.0
  barcode_scan: ^2.0.1
  pretty_qr_code: ^1.0.1
  uuid: 2.2.2
  sqflite: ^1.3.0
  random_string: ^2.1.0
  firebase_analytics:
  cloud_firestore:
  firebase_auth:
  screenshot: ^0.3.0
  permission_handler: ^5.1.0+2
  pdf: ^2.1.0
  downloads_path_provider: ^0.1.0
  path_provider:
  toast:
  clip_shadow: ^0.2.1
  firebase_storage:
  image_picker:
  geolocator:
  mapbox_gl: ^0.11.0
  auth_buttons: ^0.0.6
  modal_progress_hud: ^0.1.3
  google_sign_in: ^4.5.9
  flutter_launcher_icons: ^0.7.2+1

  flutter_test:
    sdk: flutter

flutter_icons:    
  android: true   
  ios: true    
  image_path: "assets/images/forrest_tagger_icon.png" 

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/sample_profile_image.jpg
    - assets/images/palm-tree-outline.png
    - assets/images/upload.png
    - assets/images/loading.gif
    - assets/images/illustration.png
    - assets/images/illustration2.png
    - assets/images/illustration3.png   
  

    # An image asset can refer to one or more resolution-specific "variants", see
    # https://flutter.dev/assets-and-images/#resolution-aware.

    # For details regarding adding assets from package dependencies, see
    # https://flutter.dev/assets-and-images/#from-packages

    # To add custom fonts to your application, add a fonts section here,
    # in this "flutter" section. Each entry in this list should have a
    # "family" key with the font family name, and a "fonts" key with a
    # list giving the asset and other descriptors for the font. For
    # example:
    #fonts:
    #- family: Lora
    #  fonts:
    #    - asset: assets\fonts\Lora-BoldItalic.ttf
    #     weight: 500
    #      style: italic
    #    - asset: assets\fonts\Lora-Regular.ttf
    # - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
